name: flutter_credit_card_detector
description: Um pacote Flutter que permite você implementar facilmente a interface do usuário do cartão de crédito com a detecção do cartão.
version: 0.1.6
homepage: https://github.com/weldonsouza/flutter_credit_card_detector

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.1.1
  intl: ^0.16.0
  provider: ^4.0.4
  flutter_mobx: ^1.1.0
  cupertino_icons: ^0.1.2
  flutter_masked_text: ^0.8.0
  mobx_codegen: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/
