name: flutter_credit_card_detector
description: Um pacote Flutter que permite você implementar facilmente a interface do usuário do cartão de crédito com a detecção do cartão.
version: 2.2.0
homepage: https://github.com/weldonsouza/flutter_credit_card_detector

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_masked_text2: ^0.9.1
  intl: ^0.17.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
